### ISSUE TITLE
getRoutes() doesn't return useful route info

### ISSUE THREAD

**Issue by ScottMaxson** [nxus/router#8]
The object returned by app.get('router').getRoutes() isn't expected.

This simple nxus module:

```
'use strict';

module.exports = function(app) {
  let router = app.get('router');

  router.setRoute('GET', '/', function(req, res) {
    res.send('router.getRoutes: ' + JSON.stringify(router.getRoutes()) );
  });
}
```

displays the following text on the page:

> router.getRoutes: {"isFulfilled":false,"isRejected":false}

whereas we'd expect to see something like

  [{method: "get", route: "/"} ...]

**Comment by mjreich** [comment]
@ScottMaxson that’s a promise signature. You’ll need to add a `then` like 

```javascript
router.getRoutes().then((routes) => {
  console.log(routes)
})
```

**Comment by ScottMaxson** [comment]
OK - thanks *blush* I guess one needs to read the core module and understand how the "app" object wraps other modules' functions?
